version: '3.8'

services:
  javaapp:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: javaapp-container
    container_name: javaapp-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cq5c9k08fa8c73853vvg-a.oregon-postgres.render.com:5432/conexa_test
      SPRING_DATASOURCE_USERNAME: joaquin
      SPRING_DATASOURCE_PASSWORD: RwYnzFmzYLndn78i3z6eZhm4ri9HLCDd
    volumes:
      - .:/app  # Mapea el directorio actual al directorio /app en el contenedor
      - ~/.m2:/root/.m2  # Mapea el repositorio de Maven local para caching
    working_dir: /app
    command: ./mvnw spring-boot:run  # Comando para ejecutar tu aplicación Spring Boot

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cq5c9k08fa8c73853vvg-a.oregon-postgres.render.com:5432/conexa_test
      SPRING_DATASOURCE_USERNAME: joaquin
      SPRING_DATASOURCE_PASSWORD: RwYnzFmzYLndn78i3z6eZhm4ri9HLCDd


