# Dockerfile para producción

# Usa una imagen base de Java 8 más liviana
FROM openjdk:8-jre-alpine

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia solo el archivo JAR necesario para producción
COPY target/conexa-0.0.1-SNAPSHOT.jar /app/app.jar

# Expone el puerto 8080 para que la aplicación sea accesible desde fuera del contenedor
EXPOSE 8080

# Comando para ejecutar la aplicación Spring Boot cuando se inicie el contenedor
CMD ["java", "-jar", "app.jar"]
